version: "3.7"
services:
  storage:
    build:
      context: .
      dockerfile: environment/development/storage/Dockerfile
    networks:
      - back_tier
    restart: always
    ports:
      - 27017:27017
  backend:
    build:
      context: .
      dockerfile: environment/development/backend/Dockerfile
    volumes:
      - ./app:/app/backend
    links:
      - storage
    environment:
      - STORAGE_HOST=storage
      - STORAGE_PORT=27017
      - STORAGE_DB_NAME=movies_storage
      - BACKEND_SERVER_PORT=3000
      - NODE_ENV=development
      - DEBUG=app:*
      - DEBUG_COLORS=true
    ports:
      - 3000:3000
    networks:
      - back_tier
      - front_tier
    depends_on:
      - storage
networks:
  front_tier:
  back_tier: